#!/bin/bash
# AUTOGENERATED INSTALLER FOR PROJECT SUPERIOR v43
# RUN: bash setup.sh

echo -e "\e[1;32m🔥 PROJECT SUPERIOR v43 INSTALLER 🔥\e[0m"
echo -e "\e[1;34m[1/5] Requesting Storage Access...\e[0m"
termux-setup-storage
sleep 2

echo -e "\e[1;34m[2/5] Updating Termux Repositories...\e[0m"
pkg update -y && pkg upgrade -y

echo -e "\e[1;34m[3/5] Installing System Dependencies...\e[0m"
pkg install python git tesseract rust binutils libffi openssl-tool -y

# 0. Create Directories
echo -e "\e[1;34m📂 [SETUP] Creating Directories...\e[0m"
mkdir -p logs config templates core docs
chmod 777 logs config

# 1. Install Dependencies
echo -e "\e[1;34m📦 [SETUP] Installing Python Libraries...\e[0m"
pip install -r requirements.txt --upgrade
python -c "from core.integrity import generate_checksums; generate_checksums()"

# v80: API Seeder
python -c "from core.seeder import seed_apis; seed_apis()"

echo -e "\e[1;34m[5/5] Creating Shortcut 'superior'...\e[0m"
echo "alias superior='python $PWD/main.py'" >> ~/.bashrc
source ~/.bashrc

echo -e "\e[1;34m[!] Verifying Installation...\e[0m"
python3 verify_integrity.py

if [ $? -eq 0 ]; then
    echo -e "\e[1;32m✅ INSTALLATION COMPLETE!\e[0m"
    
# v6000: BOOT PERSISTENCE (CRONTAB)
echo -e "\e[1;36m🔗 Installing Boot Persistence...\e[0m"
if command -v crontab >/dev/null; then
    (crontab -l 2>/dev/null; echo "@reboot bash $(pwd)/guardian.sh") | crontab -
    echo -e "\e[1;32m✅ Persistence Installed! Server will auto-start on boot.\e[0m"
else
    echo -e "\e[1;33m⚠️ Crontab not found. Auto-start skipped.\e[0m"
fi

echo -e "\e[1;32m✅ Setup Complete! Run 'bash guardian.sh' to start.\e[0m"
else
    echo -e "\e[1;31m❌ INSTALLATION FAILED! Check errors above.\e[0m"
fi
